import { createFileRoute } from '@tanstack/react-router'
import { LegalShell } from '@/components/legal/legal-shell'

export const Route = createFileRoute('/terms')({
  component: TermsOfService,
})

const sections = [
  {
    title: 'Acceptance of Terms',
    body: [
      'By accessing or using QuantEdge, you agree to these Terms of Service on behalf of yourself and, where applicable, your firm or employer.',
      'If you do not agree to these terms, do not use the platform.',
    ],
  },
  {
    title: 'Accounts and Workspace Access',
    body: [
      'You are responsible for maintaining accurate account information and protecting your login credentials.',
      'Firm administrators may manage team access, workspace permissions, and shared content on behalf of their organization.',
    ],
  },
  {
    title: 'Permitted Use',
    body: [
      'QuantEdge is intended for lawful financial analysis, collaboration, and workflow management. You may not use the platform to disrupt services, misuse APIs, scrape protected content, or violate applicable law.',
      'You are responsible for the accuracy of your inputs, internal approvals, and any downstream decisions made from analysis generated by the product.',
    ],
  },
  {
    title: 'Intellectual Property',
    body: [
      'QuantEdge, including its software, branding, workflows, and interface design, remains the property of QuantEdge Finance & IT and its licensors.',
      'You retain ownership of the financial models, deal data, and firm content you upload, subject to the rights needed for us to operate the service.',
    ],
  },
  {
    title: 'Disclaimers and Financial Use',
    body: [
      'QuantEdge is a software platform for analytical support and collaboration. It does not provide legal, tax, accounting, or investment advice.',
      'All models, AI commentary, and scenario outputs should be reviewed by qualified professionals before being used in business decisions.',
    ],
  },
  {
    title: 'Limitation of Liability',
    body: [
      'To the fullest extent permitted by law, QuantEdge Finance & IT is not liable for indirect, incidental, special, consequential, or punitive damages, including loss of profits, data, business opportunities, or goodwill.',
      'Our aggregate liability for any claim arising from the service will not exceed the amount paid by you or your firm to use QuantEdge during the 12 months preceding the claim.',
    ],
  },
  {
    title: 'Changes to Terms',
    body: [
      'We may update these Terms as the platform and regulatory environment evolve. Continued use after changes become effective constitutes acceptance of the revised terms.',
    ],
  },
]

function TermsOfService() {
  return (
    <LegalShell
      eyebrow='Legal / Terms'
      title='Terms of Service'
      summary='The operating rules for using QuantEdge across individual and firm workspaces.'
      effectiveDate='March 14, 2026'
      sections={sections}
    />
  )
}
